---

- name: Update all the packages
  apt:
    upgrade: dist

- name: Create SSH key for the manager
  file:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    state: "touch"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: "'controller' in group_names"

- name: Copy our SSH key for the manager
  blockinfile:
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    block: "{{ lookup('file', '~/.ssh/id_rsa') }}"
  when: "'controller' in group_names"

- name: Distribute the public key to all our hosts
  authorized_key:
    user: "ubuntu"
    state: "present"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
