---

- name: Install the packages
  apt: name={{ item }} state=latest
  with_items:
    - git

- name: Create SSH key for the manager
  file:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    state: "touch"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: inventory_hostname == "managerhost"

- name: Copy our SSH key for the manager
  blockinfile:
    dest: "/home/{{ ansible_user }}/.ssh/id_rsa"
    block: "{{ lookup('file', '~/.ssh/id_rsa') }}"
  when: inventory_hostname == "managerhost"

- name: Distribute the public key to all our hosts
  authorized_key:
    user: "ubuntu"
    state: "present"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# - debug: msg="{{ hostvars['managerhost']['manager_ssh_key']['stdout'] }}"
