---

- name: Add Flocker repo
  apt_repository:
    repo: "deb https://clusterhq-archive.s3.amazonaws.com/ubuntu/{{ ansible_distribution_version }}/$(ARCH) /"
    filename: "flocker"
    state: present

- name: Run an "apt-get update"
  apt:
    update_cache: yes

- name: Install the flocker packages on all nodes
  apt:
    name: "{{ item }}"
    allow_unauthenticated: "yes"
    state: "latest"
  with_items:
    - clusterhq-flocker-node
    - clusterhq-flocker-docker-plugin

- name: Install the flocker CLI on the manager node
  apt:
    name: "{{ item }}"
    allow_unauthenticated: "yes"
    state: "latest"
  with_items:
    - clusterhq-flocker-cli
  when: inventory_hostname == "managerhost"

- name: Download the Flocker client installer
  get_url:
    url: "{{ flocker_url }}"
    dest: "/tmp/install-flocker-client.sh"
    mode: "0755"
  when: inventory_hostname == "managerhost"

- name: Run the Flocker client installer
  command: "/tmp/install-flocker-client.sh"
  args:
    creates: /usr/local/bin/flockerctl
  when: inventory_hostname == "managerhost"

- name: Create /etc/flocker
  file:
    path: "/etc/flocker"
    state: "directory"
    mode: 0700

# - debug: msg="{{ ansible_distribution_version }}"
