---

- name: Create the VPC, Security Groups, routing and launch our Ubuntu 16.04 instances
  hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - group_vars/environment.yml

  roles:
    - aws

- name: "Preform some prep work on the instances"
  hosts: allhosts
  become: yes
  become_method: sudo
  gather_facts: false

  pre_tasks:
    - name: "Run an apt-get update"
      raw: apt-get update
    - name: "Install python 2.7"
      raw: apt-get install -qq python2.7

  vars_files:
    - group_vars/environment.yml

  roles:
    - stack

- name: "Install Docker & Flocker"
  hosts: allhosts
  become: yes
  become_method: sudo
  gather_facts: true

  vars_files:
    - group_vars/environment.yml

  roles:
    - docker-install
    - flocker-install

- name: "Generate and distribute all of the Flocker certificates before starting the services"
  hosts: allhosts
  gather_facts: true

  vars_files:
    - group_vars/environment.yml

  roles:
    - flocker-certs

- name: "Initialize the Docker Swarm cluster"
  hosts: allhosts
  become: yes
  become_method: sudo
  gather_facts: true

  vars_files:
    - group_vars/environment.yml

  roles:
    - docker-swarm
    - finish
