---

- stat: path=/tmp/swarm_worker
  register: swarm_worker

- name: Initalize the Swarm
  shell: "docker swarm join --token={{ hostvars['managerhost']['swarm_token']['stdout'] }} {{ hostvars['managerhost']['ansible_host'] }}:2377"
  args:
    creates: /tmp/swarm_worker

- name: Create a file in /tmp so we don't try and initalize the Swarm again
  file:
    path: "/tmp/swarm_worker"
    mode: "u=rw,g=r,o=r"
    state: "{{ 'file' if swarm_worker.stat.exists else 'touch' }}"

# - debug: msg="{{ hostvars['managerhost']['swarm_token']['stdout'] }}"
# - debug: msg="{{ hostvars['managerhost']['ansible_host'] }}"
